---
title: "Project1 Blog"
author: "Jiyue Zhang"
date: '2022-06-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About the project
In this project, I create a vignette for reading and summarizing recipes data by nutrients from the Food data API. After creating the function, I get a data that the max calories is less or equal than 666 since a person need 2000 calories a day, each meal should be around 666 calories. And I also want to set the min value of carbs, fat and protein to 75g, 14g and 16g. These values calculated base on the least proportion of each nutrient that we need for a meal.  

Then, I started to analyze the dataset, suprisingly, we only get 10 recipes that meet my requirements. I want to know the proportion of fat, protein and carbs in this recipie and based on the requirement of a meal to categorize them in low, normal and high three level. 

From the numeric analyze, only Greek Shrimp Orzo and Soft-Baked Pretzels are meet the requirement that has enough nutrient and calories for a meal. These two are really recommend for the people who try to be on health diet.

From the barplot, we can know that only one of the recipes that has high carbs, two of the recipes that has high fat, and three of the recipes that has high protein

From the scatterplot, we can get the name of the recipes with each nutrients level, the Trinidadian Chicken Potato Curry is both high in fat and protein but low in carbs which I think it is really interesting that can be low at carbs but high in both fat and protein. It may really good for someone who is keto diet. 

# Reflection 
The most diffcult part of logic and programming part is api is a new thing for me, even I watched the lecture doesn't mean I 100% understand the meaning and logic behind the api. Only when I practice it then I have a more deeper understanding about it. Another diffcult part is it is hard for me to find the data that is interesting or deserve to be analyzed. It is not easy to combine your programming skill with the real life analyze thing, even I choose the topic that I think is most related with my life.

The next time, I may take more time to choose the data and may also get more background about the topic before I actually start analyzing the data. In this way, I may get more interesting result from the data. 

# Links

(github pages repo)[https://github.com/jzhang96/ST558-Project1/tree/main]
(the regular repo)[https://jzhang96.github.io/ST558-Project1/]
